In [99]:
# Problem 1:
import numpy as np
arr = np.array([[1,2,3], [5,9,7], [2,4,6], [7,7,7]])

In [100]:
def onlyOdd(arrays):
    odd_rows = []
    for row in arrays:
        # Check if all values in the row are odd
        if all(value % 2 != 0 for value in row):
            odd_rows.append(row)
    
    return odd_rows


In [101]:
print(onlyOdd(arr))

[array([5, 9, 7]), array([7, 7, 7])]


In [102]:
# Problem 2.1:
def checkerboard():
    checker = np.zeros((8,8), dtype = int)
    print(checker)
    

In [103]:
checkerboard()

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [104]:
# Problem 2.2:
def checkerboard1():
    checker = np.zeros((8,8), dtype = int)
    checker[::2, ::2] = 1
    print(checker)

In [105]:
checkerboard1()

[[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]


In [106]:
# Problem 2.3:
def checkerboard2():
    checker = np.zeros((8,8), dtype = int)
    checker[::2, ::2] = 1
    checker[1::2, 1::2] = 1
    print(checker)

In [107]:
checkerboard2()

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [108]:
# Problem 2.4:
def reverse_checkerboard():
    checker = np.zeros((8,8), dtype = int)
    checker[1::2, ::2] = 1 # changes every alternate row starting from the 2nd row and every alternate column starting from the first column to 1
    checker[::2, 1::2] = 1 # changes every alternate row starting from the first row and 2nd column to 1
    print(checker)

In [109]:
reverse_checkerboard()

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [110]:
# Problem 3:
universe = np.array(['galaxy', 'clusters'])
def expansion(str, num):
    num = int(num)
    spc = " "
    space = np.char.join(spc*num, str) # adds a specified character between each character in the string
    print(space)

In [111]:
expansion(universe, 1)

['g a l a x y' 'c l u s t e r s']


In [131]:
# Problem 4:
np.random.seed(42)
planets = np.random.randint(100, 1000, (5,5))
print(planets)
def secondLargest(system):
    second_largest = []
    # transpose the matrix:
    system = system.T
    #print("Transposed matrix:\n", system)
    # now it will be easier to iterate through the rows to find the 2nd largest planet in each system:
    for i in system:
        i.sort()
        second_largest.append(i[-2])
    print(second_largest)

[[202 535 960 370 206]
 [171 800 120 714 221]
 [566 314 430 558 187]
 [472 199 971 763 230]
 [761 408 869 443 591]]


In [133]:
secondLargest(planets)

[566, 535, 960, 714, 230]
